#!/usr/bin/env bash
# Displays username, user ID, and home directory from /etc/passwd
while IFS=: read -r username password user_id group_id user_info home shell
do
    echo "$username:$user_id:$home"
done < /etc/passwd
