#!/usr/bin/env bash
# Displays /etc/passwd information as a story using while and IFS
while IFS=: read -r username password user_id group_id user_info home shell
do
    echo "The user $username is part of the $group_id gang, lives in $home and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd
